# Generated by Django 3.0.7 on 2020-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200627_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dot',
            field=models.DateTimeField(),
        ),
    ]
